# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Demos' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Demos
  pod 'Firebase'
  pod 'GoogleSignIn'

  target 'Demos-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DemosTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Demos-tvOS' do

end
