# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Demos' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Demos
  pod 'Firebase'
  pod 'FirebaseCore'
  pod 'FirebaseInstanceID'
  pod 'Google/SignIn'

end
